# file name: create-image.yml
name: create-image
on:
  push:
    tags:
      - 'v*'

jobs:
  create-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: get version
        id: get-version
        run: |
          echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: checkout
        uses: actions/checkout@v2


      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
           context: ./app/.
           push: true
           tags: amitabiswas05/test-app:${{ steps.get-version.outputs.VERSION }}

      - name: get-images-id
        id: image-id
        run: |
          echo ::set-output name=IMAGE_ID::$(docker images -q test-app:${{ steps.get-version.outputs.VERSION }})


      - name: install yq
        uses: mikefarah/yq@v4.15.1 

      - name: update infra yaml file
        run: |
          cd infra
          yq e -i '.spec.template.spec.containers[0].image="amitabiswas05/test-app:${{ steps.get-version.outputs.VERSION }}"' calc-deployment.yml
          cat calc-deployment.yml

      - name: push change
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: infra/calc-deployment.yml
          destination_repo: AMII05/CI-CD-Github-Actions-and-Argo
          destination_branch: main
          destination_folder: infra
          user_email: erbiswasami05@gmail.com
          user_name: AMII05
          commit_message: update image version ${{ steps.get_version.outputs.VERSION }} in yml file
